// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Greeting.proto

package com.beamofsoul.test.demo.grpc;

public interface GreetingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.beamofsoul.test.demo.grpc.GreetingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
