// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Greeting.proto

package com.beamofsoul.test.demo.grpc;

public final class GreetingOuterClass {
  private GreetingOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_beamofsoul_test_demo_grpc_GreetingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_beamofsoul_test_demo_grpc_GreetingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_beamofsoul_test_demo_grpc_GreetingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_beamofsoul_test_demo_grpc_GreetingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Greeting.proto\022\035com.beamofsoul.test.de" +
      "mo.grpc\"\037\n\017GreetingRequest\022\014\n\004name\030\001 \001(\t" +
      "\"#\n\020GreetingResponse\022\017\n\007message\030\001 \001(\t2w\n" +
      "\010Greeting\022k\n\010sayHello\022..com.beamofsoul.t" +
      "est.demo.grpc.GreetingRequest\032/.com.beam" +
      "ofsoul.test.demo.grpc.GreetingResponseB\002" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_beamofsoul_test_demo_grpc_GreetingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_beamofsoul_test_demo_grpc_GreetingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_beamofsoul_test_demo_grpc_GreetingRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_beamofsoul_test_demo_grpc_GreetingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_beamofsoul_test_demo_grpc_GreetingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_beamofsoul_test_demo_grpc_GreetingResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
