// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Greeting.proto

package com.beamofsoul.test.demo.grpc;

public interface GreetingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.beamofsoul.test.demo.grpc.GreetingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
